<?php

use Illuminate\Database\Seeder;
use \Illuminate\Support\Facades\DB;
use \App\Models\Supply\Request;

class BaseinfoTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::unprepared("SET FOREIGN_KEY_CHECKS=0;");
        DB::table('baseinfos')->where('id', '<=', 10000)->delete();
         DB::table('baseinfos')->insert([
             [
                 'id' => 1,
                 'type' => 'default',
                 'value' => '---',
                 'parent_id' => 0,
                 'user_can_add' => 0,
                 'user_can_view' => 0,
                 'extra_value' => '',
             ],
             [
                 'id' => 2,
                 'type' => 'categoryType',
                 'value' => 'نوع دسته بندی',
                 'parent_id' => 0,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 3,
                 'type' => 'categoryType',
                 'value' => 'موضوعی',
                 'parent_id' => 2,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 4,
                 'type' => 'degree',
                 'value' => 'مدرک تحصیلی',
                 'parent_id' => 0,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 5,
                 'type' => 'degree',
                 'value' => 'دیپلم',
                 'parent_id' => 4,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 6,
                 'type' => 'degree',
                 'value' => 'فوق دیپلم',
                 'parent_id' => 4,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 7,
                 'type' => 'degree',
                 'value' => 'کارشناسی',
                 'parent_id' => 4,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 8,
                 'type' => 'degree',
                 'value' => 'کارشناسی ارشد',
                 'parent_id' => 4,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 9,
                 'type' => 'degree',
                 'value' => 'دکتری',
                 'parent_id' => 4,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 10,
                 'type' => 'scientific_rank',
                 'value' => 'رتبه ی علمی',
                 'parent_id' => 0,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 11,
                 'type' => 'scientific_rank',
                 'value' => 'رتبه ی شماره 1',
                 'parent_id' => 10,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 12,
                 'type' => 'scientific_rank',
                 'value' => 'رتبه ی شماره 2',
                 'parent_id' => 10,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 13,
                 'type' => 'rank_requester',
                 'value' => 'سمت تقاضا کننده',
                 'parent_id' => 0,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 14,
                 'type' => 'rank_requester',
                 'value' => 'سمت شماره 1',
                 'parent_id' => 13,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 15,
                 'type' => 'rank_requester',
                 'value' => 'سمت شماره 2',
                 'parent_id' => 13,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 16,
                 'type' => 'degree_publisher',
                 'value' => 'درجه علمی نشریه',
                 'parent_id' => 0,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 17,
                 'type' => 'degree_publisher',
                 'value' => 'درجه ی علمی 1 ( نشریه )',
                 'parent_id' => 16,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 18,
                 'type' => 'degree_publisher',
                 'value' => 'درجه ی علمی 2 ( نشریه )',
                 'parent_id' => 16,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 19,
                 'type' => 'license_from',
                 'value' => 'محل مجوز',
                 'parent_id' => 0,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 20,
                 'type' => 'license_from',
                 'value' => 'محل مجوز شماره 1',
                 'parent_id' => 19,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 21,
                 'type' => 'license_from',
                 'value' => 'محل مجوز شماره 2',
                 'parent_id' => 19,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 26,
                 'type' => 'period_publisher',
                 'value' => 'دوره ی انتشار',
                 'parent_id' => 0,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 27,
                 'type' => 'period_publisher',
                 'value' => 'دوره ی انتشار 1',
                 'parent_id' => 26,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 28,
                 'type' => 'period_publisher',
                 'value' => 'دوره ی انتشار 2',
                 'parent_id' => 26,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 29,
                 'type' => 'degree_article',
                 'value' => 'درجه ی علمی مقاله',
                 'parent_id' => 0,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 30,
                 'type' => 'degree_article',
                 'value' => 'درجه ی علمی شماره 1 (مقاله)',
                 'parent_id' => 29,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
             [
                 'id' => 31,
                 'type' => 'degree_article',
                 'value' => 'درجه ی علمی شماره 2 (مقاله)',
                 'parent_id' => 29,
                 'user_can_add' => 1,
                 'user_can_view' => 1,
                 'extra_value' => '',
             ],
         ]);
        DB::unprepared("SET FOREIGN_KEY_CHECKS=1;");
        DB::unprepared("ALTER TABLE baseinfos AUTO_INCREMENT = 10000");
    }
}
