<?php

return [
    'dashboard' => 'داشبورد',
    'settings-menu' => ' تنظیمات',
    'roles-menu' => ' نقش ',
    'list-roles' => 'لیست نقش ها',
    'create-roles' => 'ثبت نقش',
    'edit-roles' => 'ویرایش نقش',
    'profile' => 'پروفایل',
    'logout' => 'خروج',
    'request-menu' => 'درخواست',
    'admins-menu' => 'ادمین',
    'list-admins' => 'لیست ادمین',
    'create-admins' => 'ثبت ادمین',
    'categories-menu' => 'دسته بندی',
    'list-categories'=>'ثبت دسته بندی',
    'create-categories'=>'ثبت دسته بندی',
    'edit-categories'=>'ویرایش دسته بندی',
    'users-menu'=>'کاربران',
    'list-users'=>'لیست کاربران',
    'publisher-menu'=>'نشریات',
    'list-publisher'=>'لیست نشریات',
    'journal-menu'=>'مجله',
    'list-journal'=>'لیست مجله',
];
